### NORMALIZATION PROBLEM
Problem #1

In [2]:
import numpy as np

# Generate a 5x5 array of random numbers (0 to 1)
X = np.random.random((5, 5))

# Calculate mean and standard deviation
mean_value = np.average(X)
std_value = np.sqrt(np.mean((X - mean_value) ** 2))

# Apply normalization: (X - mean) / std
Z = (X - mean_value) / std_value

# Save the normalized array into a .npy file
np.save("X_normalized.npy", Z)

# Display results
print("Original Array:\n", X)
print("\nMean of X:", mean_value)
print("Standard Deviation of X:", std_value)
print("\nNormalized Array:\n", Z)
print("\nFile 'X_normalized.npy' has been created.")


Original Array:
 [[0.38408669 0.69208621 0.39396253 0.24752897 0.97801215]
 [0.29945459 0.92271605 0.97466518 0.68651119 0.91926829]
 [0.5808622  0.41883017 0.11535264 0.65939541 0.55022986]
 [0.09098015 0.64073132 0.27213455 0.70890733 0.63880206]
 [0.23433053 0.72447563 0.32177025 0.69841704 0.86926418]]

Mean of X: 0.5609110076916916
Standard Deviation of X: 0.26345793781762183

Normalized Array:
 [[-0.67116717  0.4978981  -0.63368171 -1.18949551  1.58317927]
 [-0.9924029   1.37329339  1.57047525  0.47673715  1.36020683]
 [ 0.07572821 -0.53929231 -1.69119355  0.37381452 -0.04054212]
 [-1.78370355  0.30297175 -1.09610079  0.56174553  0.29564889]
 [-1.23959246  0.62083771 -0.90769995  0.52192785  1.17040758]]

File 'X_normalized.npy' has been created.


### Divisible by 3 Problem

Problem #2

In [7]:
import numpy as np

# Create an array of squares of the first 100 positive integers
A = np.arange(1, 101) ** 2
A = A.reshape(10, 10)   # reshape into 10x10

# Find all elements divisible by 3
div_by_3 = A[A % 3 == 0]

# Save result
np.save("div_by_3.npy", div_by_3)

# Print outputs
print("10x10 Array (squares of first 100 integers):\n", A)
print("\nElements divisible by 3:\n", div_by_3)
print("\nArray saved as 'div_by_3.npy'")


10x10 Array (squares of first 100 integers):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]

Array saved as 'div_by_3.npy'
